Feature/text field input mode
telekom/scale pull request #1333
Opened 2022-10-31 11:59 UTC by marvinLaubenstein

Integrating Feature Request: 

- Add inputmode support to Text Field component #1152

2022-11-03 12:43 UTC, nowseemee requested changes
This should be [input type](https://www.w3schools.com/tags/att_input_type.asp) - and it's already supported. Am I missing something?

2022-11-04 09:08 UTC, marvinLaubenstein commented
@nowseemee the [input mode](https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/) is only about the keyboard, which is provided for the text field. 
I should have named the prop inputMode, but somehow it didn't work, I get an error message from Stencil.

2022-11-04 09:16 UTC, nowseemee commented
Ah I see, thanks for explaining :)

2022-11-04 09:17 UTC, nowseemee approved these changes

2022-11-04 09:40 UTC, merged