Feat/badge
telekom/scale pull request #394
Opened 2021-06-09 12:30 UTC by Kutlovcidenis

Hi Daniel, as disscused my merge request. 
From my side, everything is good. But if not, just let me know. 
Always eager to learn new/better ways :) 

BR 
Denis

2021-06-09 13:22 UTC, nowseemee requested changes
Great work, Denis - I've left comments, please take a look and let me know what do you think. 
Can you add visual tests as well, please?

2021-06-09 13:22 UTC, nowseemee commented on packages/components/src/components/badge/badge.css
> +  --color-badge: #e20074;
please use design tokens instead of hardcoded values

2021-06-09 13:22 UTC, nowseemee commented on packages/components/src/components/badge/badge.css
> +  --inner-height-small: 88px;
can you use more `--scl-spacing-` type design tokens instead of all these magic pixel value numbers?

2021-06-09 13:22 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/Badge.stories.mdx
> +      style="text-align:center; font-size:20px; font-family:TeleNeo; color:blwhiteack; font-weight:400;"
blwhiteack? 😂

2021-06-09 13:22 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/ScaleBadge.vue
> +    size: { type: String, default: "big" },
can you remove the default values from here?

2021-06-09 13:22 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/badge_de.md
> +    <img src="assets/aa.png" alt="Accessible AA" />
use the beta badge instead

2021-06-09 13:22 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/badge.md
> +    <img src="assets/aa.png" alt="Accessible AA" />
use the beta badge instead

2021-06-09 13:22 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/badge.md
> +    <img src="assets/aa.png" alt="Accessible AA" />
`<img src="assets/beta.png" alt="Beta Component" />`

2021-06-09 13:22 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/Badge.stories.mdx
> +
can you remove the extra linebreaks, please?

2021-06-09 13:22 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/Badge.stories.mdx
> +  props: {
let's just make this `props: ScaleBadge.props` - the rest is not needed. Same goes for the other templates

2021-06-09 13:22 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/Badge.stories.mdx
> +<scale-badge style="--badge-color:blue" size:"small" >
the style attribute does nothing, right? let's remove it to avoid confusing readers

2021-06-09 13:22 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/Badge.stories.mdx
> +<scale-badge size="big" style="--badge-color:blue" rotation="0">
can you fix the indentation, please?

2021-06-09 13:22 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/Badge.stories.mdx
> +<scale-badge size="big" color="magenta" rotation="0">
indentation

2021-06-28 13:38 UTC, nowseemee requested changes
Hi Denis, thanks for your work on this. I've left comments where your attention is needed. Thanks again.

2021-06-28 13:38 UTC, nowseemee commented on packages/components/src/components/badge/badge.spec.ts
> +                color ="magenta"
this should be primary

2021-06-28 13:38 UTC, nowseemee commented on packages/components/src/components/badge/badge.spec.ts
> +  expect(page.rootInstance.color).toBe('magenta');
this should be primary

2021-06-28 13:38 UTC, nowseemee commented on packages/components/src/components/badge/readme.md
> +| `color`    | `color`    | (optional) Variant color/filling of the badge   | `"black" \| "blue" \| "magenta" \| "white"` | `undefined` |
magenta should be primary - did you forget to build the components?

2021-06-28 13:38 UTC, nowseemee commented on packages/components/src/components/badge/readme.md
> +| `size`     | `size`     | (optional) Variant size of the badge itself     | `"big" \| "small"`                          | `'big'`     |
big should be large - forgot to build?

2021-06-28 13:38 UTC, nowseemee commented on packages/components-sketch/views/badge.hbs
> +      <scale-badge size="big" color="primary" rotation="0">
big should be large instead

2021-06-28 13:38 UTC, nowseemee commented on packages/components-sketch/views/badge.hbs
> +      <scale-badge size="big" color="black" rotation="0">
big should be large instead

2021-06-28 13:38 UTC, nowseemee commented on packages/components-sketch/views/badge.hbs
> +      <scale-badge size="big" color="white" rotation="0">
big should be large instead

2021-06-28 13:38 UTC, nowseemee commented on packages/components-sketch/views/badge.hbs
> +      <scale-badge size="big" color="blue" rotation="0">
big should be large instead

2021-06-28 13:38 UTC, nowseemee commented on packages/components-sketch/views/badge.hbs
> +      <scale-badge size="big" color="primary" rotation="0">
big should be large instead

2021-06-28 13:38 UTC, nowseemee commented on packages/components-sketch/views/badge.hbs
> +      <scale-badge size="big" color="black" rotation="90">
big should be large instead

2021-06-28 13:38 UTC, nowseemee commented on packages/components-sketch/views/badge.hbs
> +      <scale-badge size="big" color="blue" rotation="30">
big should be large instead

2021-06-28 13:38 UTC, nowseemee commented on packages/components/src/components/badge/badge.css
> +  --width-big: 160px;
please rename big to large to be consistent with the prop name

2021-06-28 13:38 UTC, nowseemee commented on packages/components/src/components/badge/badge.css
> +  --inner-height-small: 88px;
please take a look again here

2021-06-28 13:38 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/Badge.stories.mdx
> +  props: {
The same goes for all the other occurrences in this file. thanks!

2021-06-28 13:38 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/Badge.stories.mdx
> +      style="text-align:center; font-size:20px; font-family:TeleNeo; color:blwhiteack; font-weight:400;"
please fix the typo

2021-06-28 13:38 UTC, nowseemee commented on packages/storybook-vue/stories/3_components/badge/badge_de.md
> +    <img src="assets/aa.png" alt="Accessible AA" />
please use the beta badge in the German file too. thanks!

2021-06-29 11:07 UTC, Kutlovcidenis commented
Hi Daniel, I think everything seems to be good know. I have my fingers crossed. Thank you again so much for the help, time and patience!

2021-07-01 10:18 UTC, Kutlovcidenis commented
Hi Daniel, as mentioned in SLACK: 
I used the tokens. Also on some other spots. Hope its okay the way I did it.
Let me know what you think/find.
Thank you!!!

2021-07-01 13:39 UTC, Kutlovcidenis commented
Fixed the Font-Family/Size 
Hoping we can finally merge *fingers crossed*

2021-07-02 07:34 UTC, merged