feat: add prop alwaysScrolled to header
telekom/scale pull request #716
Opened 2021-12-02 13:05 UTC by mato-a

# Add property alwaysScrolled to header

If this prop is set to true header will be always thin even if the page was not scrolled down.

Class `header--sticky` will be added always to the header.

This is useful for example in fullscreen mode where I'd like to make the navbar as small as possible.

2021-12-03 09:22 UTC, nowseemee commented
Thanks for your PR! 🎉 🎉 🎉 
I'll discuss this with the team and come back to you soon.

2021-12-03 09:41 UTC, nowseemee requested changes
Thanks a lot for your PR! I'd like you to change the name of the prop to `sticky` and also add this to `app-shell` and pass it down to `app-header`.

2021-12-03 09:41 UTC, nowseemee commented on packages/components/src/components/telekom/app-header/app-header.tsx
> +  @Prop() alwaysScrolled?: boolean = false;
can you rename the new prop to `sticky` please?

2021-12-03 18:27 UTC, nowseemee commented
Thanks for adding your changes. Can you please run `yarn build` in the `components` package and commit the changes? Many thanks for all your contributions!

2021-12-06 09:29 UTC, merged

2021-12-06 09:37 UTC, nowseemee commented
thanks a lot @mato-a - i'll publish this to NPM today and let you know ✌🏻

2021-12-06 09:40 UTC, mato-a commented
@nowseemee great 👍 

Thanks for guidance 😉

2021-12-06 18:27 UTC, nowseemee commented
@mato-a, it's released: `3.0.0-beta.33`